name: BoatRacing
version: ${project.version}
main: me.pafias.boatracing.BoatRacing
api-version: 1.16
author: Pafias
description: BoatRacing
depend: [ProtocolLib, helper]
commands:
  boatracing:
    usage: /boatracing
    aliases: [br, boatrace, race]
    description: BoatRacing