name: BoatRacing
version: 1.0-SNAPSHOT
main: me.pafias.boatracing.BoatRacing
api-version: 1.16
authors: [ Pafias ]
description: BoatRacing
depend: [ProtocolLib, helper]
commands:
  boatracing:
    usage: /boatracing
    aliases: [br, boatrace, race]
    description: BoatRacing